import type { Metadata } from "next";
import { Inter, Lora, Open_Sans } from "next/font/google";
import Script from "next/script";
import Link from "next/link";
import "../vendor/bootstrap/css/bootstrap.min.css";
import "../css/clean-blog.min.css";
import "../vendor/font-awesome/css/font-awesome.min.css";
// import "https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic";
// import "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lora = Lora({
  style: ["normal", "italic"],
  subsets: ["latin"],
  weight: ["400", "700"],
});
const openSan = Open_Sans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSan.className}>
        <nav className="navbar navbar-default navbar-custom navbar-fixed-top">
          <div className="container-fluid">
            <div className="navbar-header page-scroll">
              <button
                type="button"
                className="navbar-toggle"
                data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1"
              >
                <span className="sr-only">Toggle navigation</span>
                Menu <i className="fa fa-bars"></i>
              </button>
              <Link className="navbar-brand" href="/">
                Start Bootstrap
              </Link>
            </div>

            <div
              className="collapse navbar-collapse"
              id="bs-example-navbar-collapse-1"
            >
              <ul className="nav navbar-nav navbar-right">
                <li>
                  <Link href="/">Home</Link>
                </li>
                <li>
                  <Link href="/about">About</Link>
                </li>
                <li>
                  <Link href="/post">Sample Post</Link>
                </li>
                <li>
                  <Link href="/contact">Contact</Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        {children}
        <hr />
        <footer>
          <div className="container">
            <div className="row">
              <div className="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul className="list-inline text-center">
                  <li>
                    <a href="#">
                      <span className="fa-stack fa-lg">
                        <i className="fa fa-circle fa-stack-2x"></i>
                        <i className="fa fa-twitter fa-stack-1x fa-inverse"></i>
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span className="fa-stack fa-lg">
                        <i className="fa fa-circle fa-stack-2x"></i>
                        <i className="fa fa-facebook fa-stack-1x fa-inverse"></i>
                      </span>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <span className="fa-stack fa-lg">
                        <i className="fa fa-circle fa-stack-2x"></i>
                        <i className="fa fa-github fa-stack-1x fa-inverse"></i>
                      </span>
                    </a>
                  </li>
                </ul>
                <p className="copyright text-muted">
                  Copyright &copy; Your Website 2016
                </p>
              </div>
            </div>
          </div>
        </footer>
      </body>
      <Script src="./vendor/jquery/jquery.min.js" />
      <Script src="./vendor/bootstrap/js/bootstrap.min.js" />
      <Script src="./js/jqBootstrapValidation.js" />
      <Script src="./js/contact_me.js" />
      <Script src="./js/clean-blog.min.js" />
    </html>
  );
}
